#!/usr/bin/env bash
# scripts/gen-index.sh — Auto-generate the endpoint count matrix from resources/
#
# Reads every resources/*.md header ("# XXX Endpoints (N)") and writes
# resources/_endpoints-index.md. Run after updating resources (e.g. a new
# npm release) to keep the 117-endpoint number accurate forever.
#
# Usage: bash scripts/gen-index.sh
# Exit codes: 0=regenerated / 1=no endpoint files found

set -euo pipefail
cd "$(dirname "$0")/.."

OUT="resources/_endpoints-index.md"
TMP="${OUT}.tmp"

{
  echo "# Endpoint Index (auto-generated)"
  echo ""
  echo "> ⚠️ **Auto-generated by \`scripts/gen-index.sh\` — do not edit by hand.**"
  echo "> Regenerate after any resources change: \`bash scripts/gen-index.sh\`"
  echo ""
  echo "## Per-file counts"
  echo ""
  echo "| File | Endpoints | Count |"
  echo "|------|-----------|-------|"
} > "$TMP"

total=0
found=0
for f in resources/*.md; do
  [ "$(basename "$f")" = "_endpoints-index.md" ] && continue
  # Two header styles: "# X Endpoints (N)" and "# X API (N endpoints)"; strip CRLF
  count=$(tr -d '\r' < "$f" | sed -n '1p' | sed -n 's/^# .*Endpoints *(\([0-9]*\))/\1/p; s/^# .*API *(\([0-9]*\) *endpoints).*/\1/p' | head -1)
  if [ -n "$count" ]; then
    # Prefer the real endpoint list from "**Endpoints in this file**: ..." if present
    list=$(tr -d '\r' < "$f" | sed -n 's/^\*\*Endpoints in this file\*\*: //p' | head -1)
    [ -z "$list" ] && list="# ... ($count endpoints)"
    echo "| [$(basename "$f")]($(basename "$f")) | \`$list\` | $count |" >> "$TMP"
    total=$((total + count))
    found=$((found + 1))
  fi
done

if [ "$found" -eq 0 ]; then
  rm -f "$TMP"
  echo "gen-index: no endpoint-count headers found in resources/" >&2
  exit 1
fi

{
  echo ""
  echo "## Summary"
  echo ""
  echo "- Files with endpoint counts: $found"
  acct_listings=$(cat resources/*.md | tr -d '\r' | sed -n 's/^\*\*Endpoints in this file\*\*: //p' | tr ',' '\n' | sed 's/^ *//;s/ *$//' | grep -cxE 'CoinQuery|CoinStream|RequestStreamMonth')
  uniq_names=$(cat resources/*.md | tr -d '\r' | sed -n 's/^\*\*Endpoints in this file\*\*: //p' | tr ',' '\n' | sed 's/^ *//;s/ *$//' | grep -v '^$' | sort -u | wc -l | tr -d ' ')
  uniq_platform=$((total - acct_listings + 3))
  echo "- **Sum of per-file counts: $total** (cross-platform account endpoints CoinQuery/CoinStream/RequestStreamMonth are counted once per platform they appear in)"
  echo "- **Unique endpoint names across files: $uniq_names**; **unique per SKILL.md counting (account trio counted once): $uniq_platform** — see SKILL.md"
} >> "$TMP"

mv "$TMP" "$OUT"
echo "gen-index: wrote $OUT (${found} files, sum=$total)"
